

//*********************************************************************************
// These settings have been generated for use with TI-RTOS and cc26xxware
//
// Generated by SmartRF Studio version 2.3.0
// Tested with TI-RTOS version tirtos_simplelink_2_16_xx_xx
//
//*********************************************************************************


//*********************************************************************************


#include <driverlib/rf_mailbox.h>
#include <driverlib/rf_common_cmd.h>
#include <driverlib/rf_prop_cmd.h>
#include <ti/drivers/rf/RF.h>
//#include <rf_patches/rf_patch_cpe_genfsk.h>
//#include <rf_patches/rf_patch_rfe_genfsk.h>
//#include <rf_patches/rf_patch_mce_genfsk.h>
#include <rf_patches/rf_patch_rfe_ble.h>
#include <rf_patches/rf_patch_cpe_ble.h>
#include "smartrf_settings.h"


// TI-RTOS RF Mode Object
RF_Mode RF_prop =
{
    .rfMode = RF_MODE_PROPRIETARY_2_4,
    .cpePatchFxn = &rf_patch_cpe_ble,
    .mcePatchFxn = 0,
    .rfePatchFxn = &rf_patch_rfe_ble,
};


uint32_t shape[] = {0x00000000, 0x00000000, 0x00000000, 0x360c0100, 0xacaba076, 0xacacacac};


// Overrides for CMD_PROP_RADIO_SETUP
uint32_t pOverrides[] = {
//        MCE_RFE_OVERRIDE(1,0,0,1,0,0),
//        HW_REG_OVERRIDE(0x4038,0x34),
//        HW_REG_OVERRIDE(0x6088,0x3F1F),
//        HW_REG_OVERRIDE(0x608C,0x8213),
//        HW32_ARRAY_OVERRIDE(0x405C,1),
//        (uint32_t) 0x1801F800,
//        HW32_ARRAY_OVERRIDE(0x402C,1),
//        (uint32_t) 0x00608402,
//        (uint32_t) 0xc0040031,
//        (uint32_t) &shape[0],
//        (uint32_t) 0x00000343,
//        (uint32_t) 0x001000a3,
//        (uint32_t) 0x000484a3,
//        (uint32_t) 0x1c8f0583,
//        (uint32_t) 0x1c8f0543,
//        (uint32_t) 0x65980603,
//        (uint32_t) 0x00020623,
//        (uint32_t) 0x659805c3,
//        (uint32_t) 0x000205e3,
//        (uint32_t) 0x02010403,
//        HW32_ARRAY_OVERRIDE(0x4034,1),
//        (uint32_t) 0x177F0408,
//        (uint32_t) 0x00008463,
//        (uint32_t) 0x00388473,
//        (uint32_t) 0x00F388a3,
//        (uint32_t)0xFFFFFFFF,
        0x00001007, // Run patched RFE code from RAM
        0x00354038, // Synth: Set RTRIM (POTAILRESTRIM) to 5
        0x4001402D, // Synth: Correct CKVD latency setting (address)
        0x00608402, // Synth: Correct CKVD latency setting (value)
        0x4001405D, // Synth: Set ANADIV DIV_BIAS_MODE to PG1 (address)
        0x1801F800, // Synth: Set ANADIV DIV_BIAS_MODE to PG1 (value)
        0x000784A3, // Synth: Set FREF = 3.43 MHz (24 MHz / 7)
        0xA47E0583, // Synth: Set loop bandwidth after lock to 80 kHz (K2)
        0xEAE00603, // Synth: Set loop bandwidth after lock to 80 kHz (K3, LSB)
        0x00010623, // Synth: Set loop bandwidth after lock to 80 kHz (K3, MSB)
        0x00456088, // Adjust AGC reference level
        0x013800C3, // Use enhanced BLE shape,
        0xFFFFFFFF, // End of override list
};

// CMD_PROP_RADIO_SETUP
rfc_CMD_PROP_RADIO_SETUP_t RF_cmdPropRadioDivSetup =
{
    .commandNo = 0x3806,
    .status = 0x0000,
    .pNextOp = 0, // INSERT APPLICABLE POINTER: (uint8_t*)&xxx
    .startTime = 0x00000000,
    .startTrigger.triggerType = 0x0,
    .startTrigger.bEnaCmd = 0x0,
    .startTrigger.triggerNo = 0x0,
    .startTrigger.pastTrig = 0x0,
    .condition.rule = 0x1,
    .condition.nSkip = 0x0,
    .modulation.modType = 0x1,
    .modulation.deviation = 200,
    .symbolRate.preScale = 15,
    .symbolRate.rateWord = 131072,
    .rxBw = 7,
    .preamConf.nPreamBytes = 0x8,
    .preamConf.preamMode = 0x0,
    .formatConf.nSwBits = 16,
    .formatConf.bBitReversal = 0x0,
    .formatConf.bMsbFirst = 0x1,
    .formatConf.fecMode = 0x0,
    .formatConf.whitenMode = 0x0,
    .config.frontEndMode = 0x0,
    .config.biasMode = 0x0,
    .config.analogCfgMode = 0x0,
    .config.bNoFsPowerUp = 0x0,
    .txPower = 0x9324,
    .pRegOverride = pOverrides,
};

rfc_CMD_RADIO_SETUP_t RF_cmdRadioSetup =
{
    .commandNo = CMD_RADIO_SETUP,
    .status = 0x0000,
    .pNextOp = 0, // INSERT APPLICABLE POINTER: (uint8_t*)&xxx
    .startTime = 0x00000000,
    .startTrigger.triggerType = 0x0,
    .startTrigger.bEnaCmd = 0x0,
    .startTrigger.triggerNo = 0x0,
    .startTrigger.pastTrig = 0x0,
    .condition.rule = 0x1, // Never
    .condition.nSkip = 0x0,
    .mode = 0,
    .txPower = 0x9330,
    .pRegOverride = pOverrides,
};


// CMD_FS
rfc_CMD_FS_t RF_cmdFs =
{
    .commandNo = 0x0803,
    .status = 0x0000,
    .pNextOp = 0, // INSERT APPLICABLE POINTER: (uint8_t*)&xxx
    .startTime = 0x00000000,
    .startTrigger.triggerType = 0x0,
    .startTrigger.bEnaCmd = 0x0,
    .startTrigger.triggerNo = 0x0,
    .startTrigger.pastTrig = 0x0,
    .condition.rule = 0x1,
    .condition.nSkip = 0x0,
    .frequency = 2440,
    .fractFreq = 0x0000,
    .synthConf.bTxMode = 1,
    .synthConf.refFreq = 0x0,
};

// CMD_PROP_TX
rfc_CMD_PROP_TX_t RF_cmdPropTx =
{
    .commandNo = 0x3801,
    .status = 0x0000,
    .pNextOp = 0, // INSERT APPLICABLE POINTER: (uint8_t*)&xxx
    .startTime = 0x00000000,
    .startTrigger.triggerType = 0x0,
    .startTrigger.bEnaCmd = 0x0,
    .startTrigger.triggerNo = 0x0,
    .startTrigger.pastTrig = 0x0,
    .condition.rule = 0x1,
    .condition.nSkip = 0x0,
    .pktConf.bFsOff = 0x0,
    .pktConf.bUseCrc = 0x1,
    .pktConf.bVarLen = 0x1,
    .pktLen = 0x1e, // SET APPLICATION PAYLOAD LENGTH
    .syncWord = 0xD391D391,
    .pPkt = 0, // INSERT APPLICABLE POINTER: (uint8_t*)&xxx
};

// CMD_PROP_RX
rfc_CMD_PROP_RX_t RF_cmdPropRx =
{
    .commandNo = 0x3802,
    .status = 0x0000,
    .pNextOp = 0, // INSERT APPLICABLE POINTER: (uint8_t*)&xxx
    .startTime = 0x00000000,
    .startTrigger.triggerType = 0x0,
    .startTrigger.bEnaCmd = 0x0,
    .startTrigger.triggerNo = 0x0,
    .startTrigger.pastTrig = 0x0,
    .condition.rule = 0x1,
    .condition.nSkip = 0x0,
    .pktConf.bFsOff = 0x0,
    .pktConf.bRepeatOk = 0x0,
    .pktConf.bRepeatNok = 0x0,
    .pktConf.bUseCrc = 0x1,
    .pktConf.bVarLen = 0x1,
    .pktConf.bChkAddress = 0x0,
    .pktConf.endType = 0x0,
    .pktConf.filterOp = 0x0,
    .rxConf.bAutoFlushIgnored = 0x0,
    .rxConf.bAutoFlushCrcErr = 0x0,
    .rxConf.bIncludeHdr = 0x1,
    .rxConf.bIncludeCrc = 0x0,
    .rxConf.bAppendRssi = 0x0,
    .rxConf.bAppendTimestamp = 0x0,
    .rxConf.bAppendStatus = 0x1,
    .syncWord = 0xD391D391,
    .maxPktLen = 0x7d, // MAKE SURE DATA ENTRY IS LARGE ENOUGH
    .address0 = 0xaa,
    .address1 = 0xbb,
    .endTrigger.triggerType = 0x1,
    .endTrigger.bEnaCmd = 0x0,
    .endTrigger.triggerNo = 0x0,
    .endTrigger.pastTrig = 0x0,
    .endTime = 0x00000000,
    .pQueue = 0, // INSERT APPLICABLE POINTER: (dataQueue_t*)&xxx
    .pOutput = 0, // INSERT APPLICABLE POINTER: (uint8_t*)&xxx
};

// CMD_TX_TEST
rfc_CMD_TX_TEST_t RF_cmdTxTest =
{
        .commandNo = 0x0808,
        .status = 0x0000,
        .pNextOp = 0, /*INSERT APPLICABLE POINTER: (uint8_t*)&xxx */
        .startTime = 0x00000000,
        .startTrigger.triggerType = 0x0,
        .startTrigger.bEnaCmd = 0x0,
        .startTrigger.triggerNo = 0x0,
        .startTrigger.pastTrig = 0x0,
        .condition.rule = 0x1,
        .condition.nSkip = 0x0,
        .config.bUseCw = 0x0,
        .config.bFsOff = 0x0,
        .config.whitenMode = 0x2,
        .__dummy0 = 0x00,
        .txWord = 0xabcd,
        .__dummy1 = 0x00,
        .endTrigger.triggerType = 0x1,
        .endTrigger.bEnaCmd = 0x0,
        .endTrigger.triggerNo = 0x0,
        .endTrigger.pastTrig = 0x0,
        .syncWord = 0x930b51de,
        .endTime = 0x00000000,
};
